spring.application.name=mcm-backend

spring.datasource.url=jdbc:sqlite:db/mcm.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=com.mcm.config.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect